import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font_family)"],
      },
      backgroundColor: {
        'brand-primary': 'var(--bg_brand_primary)',
        'brand-secondary': 'var(--bg_brand_secondary)',
        'brand-solid': 'var(--bg_brand_solid)',
        'brand-solid-hover': 'var(--bg_brand_solid_hover)',
        'disabled': 'var(--bg_disabled)',
        'elevated': 'var(--bg_elevated)',
        'error-primary': 'var(--bg_error_primary)',
        'error-solid': 'var(--bg_error_solid)',
        'info-primary': 'var(--bg_info_primary)',
        'info-solid': 'var(--bg_info_solid)',
        'overlay': 'var(--bg_overlay)',
        'primary': 'var(--bg_primary)',
        'quaternary': 'var(--bg_quaternary)',
        'secondary': 'var(--bg_secondary)',
        'success-primary': 'var(--bg_success_primary)',
        'success-solid': 'var(--bg_success_solid)',
        'tertiary': 'var(--bg_tertiary)',
        'warning-primary': 'var(--bg_warning_primary)',
        'warning-solid': 'var(--bg_warning_solid)',
        card: 'var(--bg_elevated)',
        popover: 'var(--bg_elevated)',
        muted: 'var(--bg_tertiary)',
        accent: 'var(--bg_tertiary)',
        destructive: 'var(--bg_error_solid)',
        'sidebar': 'var(--bg_sidebar)',
        'sidebar-hover': 'var(--bg_sidebar_hover)',
        'sidebar-active': 'var(--bg_sidebar_active)',
        'auth-panel': 'var(--bg_auth_panel)',
        'neutral-solid': 'var(--bg_neutral_solid)',
        'selected': 'var(--bg_selected)',
      },
      textColor: {
        'brand': 'var(--text_brand)',
        'brand-secondary': 'var(--text_brand_secondary)',
        'disabled': 'var(--text_disabled)',
        'error': 'var(--text_error)',
        'info': 'var(--text_info)',
        'placeholder': 'var(--text_placeholder)',
        'primary': 'var(--text_primary)',
        'quaternary': 'var(--text_quaternary)',
        'secondary': 'var(--text_secondary)',
        'success': 'var(--text_success)',
        'tertiary': 'var(--text_tertiary)',
        'warning': 'var(--text_warning)',
        'white': 'var(--text_white)',
        foreground: 'var(--text_primary)',
        'muted-foreground': 'var(--text_tertiary)',
        'primary-foreground': 'var(--text_white)',
        'sidebar': 'var(--text_sidebar)',
        'sidebar-muted': 'var(--text_sidebar_muted)',
        'sidebar-label': 'var(--text_sidebar_label)',
        'sidebar-active': 'var(--text_sidebar_active)',
        'link': 'var(--text_link)',
        'link-hover': 'var(--text_link_hover)',
        'icon-brand': 'var(--icon_brand)',
      },
      borderColor: {
        'brand': 'var(--border_brand)',
        'brand-solid': 'var(--border_brand_solid)',
        'control': 'var(--border_control)',
        'control-hover': 'var(--border_control_hover)',
        'disabled': 'var(--border_disabled)',
        'error': 'var(--border_error)',
        'error-solid': 'var(--border_error_solid)',
        'hover': 'var(--border_hover)',
        'info': 'var(--border_info)',
        'primary': 'var(--border_primary)',
        'secondary': 'var(--border_secondary)',
        'success': 'var(--border_success)',
        'success-solid': 'var(--border_success_solid)',
        'tertiary': 'var(--border_tertiary)',
        'warning': 'var(--border_warning)',
        DEFAULT: 'var(--border_secondary)',
        input: 'var(--border_primary)',
        border: 'var(--border_primary)',
        'sidebar': 'var(--border_sidebar)',
        'warning-solid': 'var(--border_warning_solid)',
      },
      ringColor: {
        brand: 'var(--border_brand)',
      },
      borderRadius: {
        lg: 'var(--radius_md)',
        md: 'calc(var(--radius_md) - 2px)',
        sm: 'calc(var(--radius_md) - 4px)',
      },
    },
  },
  plugins: [],
}
export default config
